language: ruby
rvm:
        - 1.9.3
env:
        - DB=sqlite
bundler_args: --without development
script:
        - RAILS_ENV=test bundle exec rake db:migrate --trace
        - bundle exec cucumber -f progress -r features
        - bundle exec rspec spec
